{% set name = "google-cloud-videointelligence" %}
{% set version = "2.3.3" %}
{% set sha256 = "bb3a98b5b8044be80c5fdbd76e7acd9b9bdd6026729a53eae9692a9a6c6683ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.10.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.videointelligence
    - google.cloud.videointelligence_v1

about:
  home: https://github.com/googleapis/python-videointelligence
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Video Intelligence API client library
  description: "Google Cloud Video Intelligence API is a Google Cloud service that makes videos searchable, and discoverable, by extracting metadata with an easy to use API. You can now search every moment of every video file in your catalog and find every occurrence as well as its significance. It quickly annotates videos\
    \ stored in Google Cloud Storage, and helps you identify key nouns entities of your video, and when they occur within the video. Separate signal from noise, by retrieving relevant information at the video, shot or per frame.\nSee the [quick start guide](https://googleapis.dev/python/videointelligence/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/videointelligence/latest/index.html
  dev_url: https://github.com/googleapis/python-videointelligence

extra:
  recipe-maintainers:
    - parthea
